name = "elipecas"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

main = ".output/server/index.mjs"

# NecessÃ¡rio para Pages Functions
pages_build_output_dir = ".output/public"
